// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld/src/HelloWorld.vue')['default']
    IconMsDarkModeOutline: typeof import('~icons/material-symbols/dark-mode-outline')['default']
    IconMsLightModeOutline: typeof import('~icons/material-symbols/light-mode-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
